# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 901fcc7b134cb3de25133892bdd39433cbc320aecfce53f7e8afe2cf46e17b34df2383e6ab828f73ff193801494b42d0e592d649c9a50ef88ddfd595b7c8fed3

test:
  secret_key_base: 81ebfc2a214008f3a9442c2445845b80ccb3bcbfdc817ff1b40d5bf789d7f075934438e66a7426431b8d6e537a610aedff6aa1deeea364dc7db3b7b4c69b3f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
